name: secondshop
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


#------------------packages--------------------
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state_management
  get: ^4.6.6
  get_storage: ^2.1.1

  # product specific



  #-------------,/packages end--------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

 #-------------Local Assets---------
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/

 #-----------Local fonts-------------
  fonts:
    - family:
    -  fonts:





  


